### ISSUE TITLE
Credit this link

### ISSUE THREAD

**Issue by hueychen27** [yoyomonem/programscript#1]
From the code, I can tell that you used this tutorial: https://www.youtube.com/playlist?list=PL_2VhOvlMk4UHGqYCLWc6GO8FaPl8fQTh  
If you want to, you can credit the Youtube tutorial.

**Comment by yoyomonem** [comment]
Done in https://github.com/yoyomonem/programscript/commit/87159b5456be70711a31fc5d97fe578aef1830f2.
